// app/src/lib/components/Header.svelte
<script lang="ts">
  import { page } from "$app/state";
  import { feed } from "$lib/feed.svelte";
  import { theme } from "$lib/theme.svelte";

  const NAV = [
    { href: "/", label: "Feed" },
    { href: "/internships", label: "Internships" },
    { href: "/settings", label: "Settings" },
  ];

  const themeIcon = $derived(
    theme.value === "light" ? "☀️" : theme.value === "dark" ? "🌙" : "🖥️",
  );
</script>

<header
  class="glass safe-top sticky top-0 z-40 border-b border-zinc-200 dark:border-zinc-800"
>
  <div class="mx-auto flex h-14 w-full max-w-6xl items-center justify-between gap-3 px-4 sm:px-6">
    <a href="/" class="flex shrink-0 items-center gap-2">
      <span
        class="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-600 to-violet-600 text-xs font-bold text-white"
      >
        AF
      </span>
      <span class="font-display hidden text-lg font-bold sm:block">Anti-FOMO</span>
    </a>

    <nav class="flex items-center gap-1">
      {#each NAV as link (link.href)}
        <a
          href={link.href}
          class="rounded-lg px-3 py-1.5 text-sm font-semibold transition-colors {page.url
            .pathname === link.href
            ? 'bg-zinc-900 text-white dark:bg-white dark:text-zinc-900'
            : 'text-zinc-600 hover:bg-zinc-100 dark:text-zinc-400 dark:hover:bg-zinc-800'}"
        >
          {link.label}
        </a>
      {/each}
    </nav>

    <div class="flex shrink-0 items-center gap-1">
      <button
        onclick={() => theme.cycle()}
        title="Theme: {theme.value}"
        aria-label="Switch theme"
        class="flex h-8 w-8 items-center justify-center rounded-lg text-sm transition-colors hover:bg-zinc-100 dark:hover:bg-zinc-800"
      >
        {themeIcon}
      </button>
      <button
        onclick={() => feed.refresh(true)}
        disabled={feed.refreshing}
        title="Refresh all sources"
        aria-label="Refresh"
        class="flex h-8 w-8 items-center justify-center rounded-lg text-sm transition-colors hover:bg-zinc-100 disabled:opacity-50 dark:hover:bg-zinc-800"
      >
        <span class="inline-block {feed.refreshing ? 'animate-spin' : ''}">↻</span>
      </button>
    </div>
  </div>
</header>

// frontend/src/components/Header.tsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { getToken } from "../lib/api";

const NAV = [
  { href: "/", label: "Feed", key: "feed" },
  { href: "/internships", label: "Internships", key: "internships" },
] as const;

export default function Header({
  active,
  children,
}: {
  active?: "feed" | "internships" | "hub";
  children?: React.ReactNode;
}) {
  const [signedIn, setSignedIn] = useState(false);

  useEffect(() => {
    setSignedIn(getToken() !== null);
  }, []);

  return (
    <header className="sticky top-0 z-20 w-full border-b border-zinc-200 glass dark:border-zinc-800">
      <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 p-4 flex-wrap">
        <Link href="/" className="flex items-center gap-2 shrink-0">
          <div className="h-8 w-8 rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center text-white font-bold shadow-sm">
            AF
          </div>
          <h1 className="text-xl font-bold tracking-tight">Anti-FOMO</h1>
        </Link>

        <nav className="flex items-center gap-1 text-sm font-medium">
          {NAV.map((n) => (
            <Link
              key={n.key}
              href={n.href}
              className={`rounded-full px-3.5 py-1.5 transition-colors ${
                active === n.key
                  ? "bg-indigo-600/10 text-indigo-600 dark:bg-indigo-400/10 dark:text-indigo-400"
                  : "text-zinc-500 hover:text-zinc-900 dark:hover:text-zinc-100"
              }`}
            >
              {n.label}
            </Link>
          ))}
          <Link
            href={signedIn ? "/dashboard" : "/login"}
            className={`ml-2 rounded-full px-4 py-1.5 font-semibold transition-all ${
              active === "hub"
                ? "bg-indigo-600 text-white"
                : "bg-indigo-600 text-white hover:bg-indigo-500 hover:shadow-md hover:shadow-indigo-600/20"
            }`}
          >
            {signedIn ? "Student Hub" : "Sign in"}
          </Link>
        </nav>

        {children && <div className="w-full md:w-auto md:flex-1 md:order-none order-last">{children}</div>}
      </div>
    </header>
  );
}
